# Generated by Django 5.0.2 on 2024-03-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='email',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='password',
        ),
    ]
